# Generated by Django 5.2 on 2025-04-21 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='children', to='registry.animal'),
        ),
    ]
