# Generated by Django 5.2 on 2025-04-21 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_animal_parents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='parents',
        ),
        migrations.AddField(
            model_name='animal',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring_father', to='registry.animal'),
        ),
        migrations.AddField(
            model_name='animal',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring_mother', to='registry.animal'),
        ),
    ]
