# Generated by Django 5.2 on 2025-04-21 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_remove_animal_parents_animal_father_animal_mother'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['species'], name='registry_an_species_401cd1_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['breed'], name='registry_an_breed_02e625_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['registration_date'], name='registry_an_registr_45afd6_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['father'], name='registry_an_father__3f34a5_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['mother'], name='registry_an_mother__7282b5_idx'),
        ),
    ]
